stages:
- build
- test
- deploy

sast:
  stage: test
  script: 
    - echo "HelloWorld"

mobsfscan:
  stage: test
  image: python
  before_script:
    - pip3 install --upgrade mobsfscan
  script:
    - mobsfscan . --json -o mobsf-sast-report.json
  artifacts:
    paths:
      - mobsf-sast-report.json

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
